/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/recommendations/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/create`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/details`; params?: Router.UnknownInputParams; } | { pathname: `/services/PerformanceService`; params?: Router.UnknownInputParams; } | { pathname: `/services/StatsService`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/athlete/insights/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/athlete/measurements/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/athlete/performance-history/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/athlete/performance-measurements/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/athlete/view-measurements/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/athlete/recommendations/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/athlete/create`; params?: Router.UnknownOutputParams; } | { pathname: `/athlete/details`; params?: Router.UnknownOutputParams; } | { pathname: `/services/PerformanceService`; params?: Router.UnknownOutputParams; } | { pathname: `/services/StatsService`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/athlete/insights/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/athlete/measurements/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/athlete/performance-history/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/athlete/performance-measurements/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/athlete/view-measurements/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/athlete/recommendations/[id]${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/athlete/create${`?${string}` | `#${string}` | ''}` | `/athlete/details${`?${string}` | `#${string}` | ''}` | `/services/PerformanceService${`?${string}` | `#${string}` | ''}` | `/services/StatsService${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/recommendations/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/create`; params?: Router.UnknownInputParams; } | { pathname: `/athlete/details`; params?: Router.UnknownInputParams; } | { pathname: `/services/PerformanceService`; params?: Router.UnknownInputParams; } | { pathname: `/services/StatsService`; params?: Router.UnknownInputParams; } | `/+not-found` | `/athlete/insights/${Router.SingleRoutePart<T>}` | `/athlete/measurements/${Router.SingleRoutePart<T>}` | `/athlete/performance-history/${Router.SingleRoutePart<T>}` | `/athlete/performance-measurements/${Router.SingleRoutePart<T>}` | `/athlete/view-measurements/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/athlete/insights/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/athlete/measurements/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/athlete/performance-history/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/athlete/performance-measurements/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/athlete/view-measurements/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
